kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: quay.io/coreos/jsonnet-ci
  commands:
  - cd examples && jb install && cd ..
  - make
  - git diff --exit-code
